### PR TITLE
backend/drm/libliftoff.c: add additional options parameter

### PR DESCRIPTION
**Pull request by MarkusVolk**
This fixes build with libliftoff 0.5.0
| ../git/subprojects/wlroots-hyprland/backend/drm/libliftoff.c: In function 'commit': | ../git/subprojects/wlroots-hyprland/backend/drm/libliftoff.c:410:27: error: too few arguments to function 'liftoff_output_apply'
|   410 |                 int ret = liftoff_output_apply(crtc->liftoff, req, flags);

### CODE REVIEW

**Comment by vaxerski** [comment]
is there no #define guard there for folks on liftoff < 0.5?

**Comment by MarkusVolk** [comment]
> is there no #define guard there for folks on liftoff < 0.5?

I have to admit that I dont really like that kind of guards. II would wait until the big distributions provide 0.5 and then just require it in meson.build

Anyway, sent this mostly to highlight that there is a breaking change in libliftoff

**Comment by Consolatis** [comment]
MR on the upstream side: https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/4697

**Comment by vaxerski** [comment]
I have to admit I don't really like breaking api in such a way. heh

**Comment by MarkusVolk** [comment]
> I have to admit I don't really like breaking api in such a way. heh

Undisputed.
But now that there is an official patch for this problem in wlroots, this request can probably be closed

**Comment by vaxerski** [comment]
is it merged yet? otherwise we'd have to put it as a patch

**Comment by MarkusVolk** [comment]
Updated the request with the official patch

Or do you want to have this in the patches directory as long as it wasn't merged?

**Comment by vaxerski** [comment]
would be nice to put it in patches/ to keep the tree clean

**Comment by Consolatis** [comment]
@MarkusVolk are you fine with me submitting your patch as a backport MR to wlroots 0.17?

Edit:
Sorry, just saw that the upstream MR was changed already. Disregard the question then.

**Review by vaxerski — APPROVED** [review]
thanks!
